---
# tasks file for install_Docker

- name: install Docker Dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: add user to docker group
  user: 
    name: brian
    groups: docker
    append: yes

- name: add user as docker.sock owner
  raw: chown brian:docker /var/run/docker.sock